### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Falieson** [dawsonbotsford/skrub-cli#1]
```
$ npm install --global skrub-cli
$ touch sample
$ skrub sample
/usr/local/lib/node_modules/skrub-cli/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by dawsonbotsford** [comment]
Can you paste the output of [sist](https://github.com/dawsonbotsford/sist) with the command

```
sist node shell
```

to help find out your versions and Operating System? Thanks 👍

**Comment by dawsonbotsford** [comment]
It's very likely a node version issue. Update your node version and try again. [source](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)

**Comment by Falieson** [comment]
$ npm version
{ npm: '3.8.6',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }

**Comment by Falieson** [comment]
Absolutely right, needed to upgrade Node! Thanks.
