### ISSUE TITLE
skrub improperly selected dir

### ISSUE THREAD

**Issue by Falieson** [dawsonbotsford/skrub-cli#2]
Not a true error if one knows what they are trying to do but rm will remove a directory whether or not it has a trailing slash.

```bash
$ mkdir Empty
$ skrub Empty
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/Users/{}/Code/Empty'
    at Error (native)

$ skrub Empty/
$
```

**Comment by dawsonbotsford** [comment]
File globbing issues belong with the file-globbing library [globby](https://github.com/sindresorhus/globby) or more likely the pattern matching library globby uses called [minimatch](https://github.com/isaacs/minimatch#usage).

If this issue truly pertains to this project feel free to reopen. Thanks! 👍
